/**
 * Autonomous Knowledge Package Generation Service
 * 
 * Automatically generates Knowledge Packages from discovered topics
 * No manual intervention required
 */

import { getAdminClient } from "@/lib/supabase/clientFactory";

const supabase = getAdminClient();

/**
 * Generate Knowledge Package for a discovered topic
 */
export async function generateKnowledgePackage(topicSlug: string, discoveredData: any): Promise<void> {
  console.log(`Generating Knowledge Package for: ${topicSlug}`);

  // Import the assemble function from existing pipeline
  const { assemble } = await import("../knowledge/assembler");

  // Create candidates from discovered data with proper types
  const candidates = [{
    id: `candidate-${topicSlug}-${Date.now()}`,
    title: discoveredData.title,
    description: discoveredData.description,
    sourceUrl: discoveredData.sourceUrl,
    discoveryRunId: `run-${Date.now()}`,
    adapterName: discoveredData.adapterName,
    sourceSlug: topicSlug,
    sourceAuthority: "high" as any, // Type cast to avoid strict type checking for now
    metadata: {
      autoGenerated: true,
      discoveredAt: new Date().toISOString()
    }
  }];

  // Run assembly
  const result = await assemble({
    slotId: null,
    topicId: null,
    slug: topicSlug,
    candidates: candidates
  });

  console.log(`Knowledge Package generated for ${topicSlug}:`, result);

  // Update queue item status
  await updateQueueItemStatus(topicSlug, "assembled", { success: true });
}

/**
 * Process all discovered topics and generate Knowledge Packages
 */
export async function processAssemblyQueue(): Promise<void> {
  const { data: queueItems, error: fetchError } = await supabase
    .from("content_generation_queue")
    .select("*")
    .eq("status", "discovered")
    .lt("attempts", 3)
    .limit(10);

  if (fetchError) {
    throw new Error(`Failed to fetch assembly queue: ${fetchError.message}`);
  }

  if (!queueItems || queueItems.length === 0) {
    console.log("No topics in assembly queue");
    return;
  }

  console.log(`Processing ${queueItems.length} topics from assembly queue`);

  for (const item of queueItems) {
    try {
      // Increment attempt counter
      const { error: updateError } = await supabase
        .from("content_generation_queue")
        .update({ attempts: (item.attempts || 0) + 1 })
        .eq("id", item.id);

      if (updateError) {
        console.error(`Failed to increment attempt counter for ${item.topic_slug}: ${updateError.message}`);
      }

      if (item.discovered_data) {
        await generateKnowledgePackage(item.topic_slug, item.discovered_data);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`Failed to process ${item.topic_slug} (attempt ${item.attempts + 1}): ${message}`);
      if ((item.attempts || 0) + 1 >= (item.max_attempts || 3)) {
        await updateQueueItemStatus(item.topic_slug, "failed", { error: message, maxAttemptsReached: true });
      } else {
        await updateQueueItemStatus(item.topic_slug, "failed", { error: message });
      }
    }
  }
}

/**
 * Update queue item status
 */
async function updateQueueItemStatus(topicSlug: string, status: string, metadata: any): Promise<void> {
  const { error } = await supabase
    .from("content_generation_queue")
    .update({
      status,
      metadata,
      updated_at: new Date().toISOString()
    })
    .eq("topic_slug", topicSlug);

  if (error) {
    console.error(`Failed to update queue status for ${topicSlug} to ${status}: ${error.message}`);
  }
}

/**
 * Run continuous assembly loop
 */
export async function runContinuousAssembly(): Promise<void> {
  console.log("Starting continuous assembly loop...");

  while (true) {
    await processAssemblyQueue();

    // Wait 5 minutes before next check
    await new Promise(resolve => setTimeout(resolve, 5 * 60 * 1000));
  }
}
