/**
 * Autonomous Knowledge Package Generation Service
 * 
 * Automatically generates Knowledge Packages from discovered topics
 * No manual intervention required
 */

import { getAdminClient } from "@/lib/supabase/clientFactory";

const supabase = getAdminClient();

/**
 * Generate Knowledge Package for a discovered topic
 */
export async function generateKnowledgePackage(topicSlug: string, discoveredData: any): Promise<void> {
  console.log(`Generating Knowledge Package for: ${topicSlug}`);

  try {
    // Import the assemble function from existing pipeline
    const { assemble } = await import("../knowledge/assembler");

    // Create candidates from discovered data with proper types
    const candidates = [{
      id: `candidate-${topicSlug}-${Date.now()}`,
      title: discoveredData.title,
      description: discoveredData.description,
      sourceUrl: discoveredData.sourceUrl,
      discoveryRunId: `run-${Date.now()}`,
      adapterName: discoveredData.adapterName,
      sourceSlug: topicSlug,
      sourceAuthority: "high" as any, // Type cast to avoid strict type checking for now
      metadata: {
        autoGenerated: true,
        discoveredAt: new Date().toISOString()
      }
    }];

    // Run assembly
    const result = await assemble({
      slotId: null,
      topicId: null,
      slug: topicSlug,
      candidates: candidates
    });

    console.log(`Knowledge Package generated for ${topicSlug}:`, result);

    // Update queue item status
    await updateQueueItemStatus(topicSlug, "assembled", { success: true });

  } catch (error) {
    console.error(`Error generating Knowledge Package for ${topicSlug}:`, error);
    await updateQueueItemStatus(topicSlug, "failed", { error: String(error) });
  }
}

/**
 * Process all discovered topics and generate Knowledge Packages
 */
export async function processAssemblyQueue(): Promise<void> {
  const { data: queueItems } = await supabase
    .from("content_generation_queue")
    .select("*")
    .eq("status", "discovered")
    .lt("attempts", 3) // Only process items that haven't exceeded max attempts
    .limit(10);

  if (!queueItems || queueItems.length === 0) {
    console.log("No topics in assembly queue");
    return;
  }

  console.log(`Processing ${queueItems.length} topics from assembly queue`);

  for (const item of queueItems) {
    try {
      // Increment attempt counter
      await supabase
        .from("content_generation_queue")
        .update({ attempts: (item.attempts || 0) + 1 })
        .eq("id", item.id);

      if (item.discovered_data) {
        await generateKnowledgePackage(item.topic_slug, item.discovered_data);
      }
    } catch (error) {
      console.error(`Failed to process ${item.topic_slug} (attempt ${item.attempts + 1}):`, error);
      // If max attempts reached, mark as failed
      if ((item.attempts || 0) + 1 >= (item.max_attempts || 3)) {
        await updateQueueItemStatus(item.topic_slug, "failed", { error: String(error), maxAttemptsReached: true });
      }
    }
  }
}

/**
 * Update queue item status
 */
async function updateQueueItemStatus(topicSlug: string, status: string, metadata: any): Promise<void> {
  await supabase
    .from("content_generation_queue")
    .update({
      status,
      metadata,
      updated_at: new Date().toISOString()
    })
    .eq("topic_slug", topicSlug);
}

/**
 * Run continuous assembly loop
 */
export async function runContinuousAssembly(): Promise<void> {
  console.log("Starting continuous assembly loop...");

  while (true) {
    await processAssemblyQueue();

    // Wait 5 minutes before next check
    await new Promise(resolve => setTimeout(resolve, 5 * 60 * 1000));
  }
}
