/**
 * Generate knowledge packages for all existing topics
 */

import * as dotenv from "dotenv";
import { resolve } from "path";

dotenv.config({ path: resolve(process.cwd(), ".env.local") });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "crypto";

const supabase = createClient(supabaseUrl, supabaseKey);

function generateUUID(): string {
  return randomUUID();
}

async function generateKnowledgePackages(): Promise<void> {
  console.log("Generating knowledge packages for all topics...");

  const { data: topics, error } = await supabase
    .from("topics")
    .select("id, slug");

  if (error) {
    console.error("Error querying topics:", error);
    return;
  }

  if (!topics || topics.length === 0) {
    console.log("No topics found");
    return;
  }

  console.log(`Found ${topics.length} topics`);

  let successCount = 0;
  let failCount = 0;

  for (const topic of topics) {
    try {
      // Import the assemble function
      const { assemble } = await import("../services/knowledge/assembler");

      // Create candidate from topic metadata
      const candidates = [{
        id: generateUUID(),
        title: topic.slug.split("-").map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(" "),
        description: `Learn about ${topic.slug.split("-").map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}`,
        sourceUrl: `https://valendiro.com/en/topics/${topic.slug}`,
        discoveryRunId: generateUUID(),
        adapterName: "topic-generator",
        sourceSlug: topic.slug,
        sourceAuthority: "high" as any,
        metadata: {
          autoGenerated: true,
          topicId: topic.id,
          discoveredAt: new Date().toISOString()
        }
      }];

      // Run assembly
      const result = await assemble({
        slotId: null,
        topicId: topic.id,
        slug: topic.slug,
        candidates: candidates
      });

      console.log(`✓ Generated knowledge package: ${topic.slug}`);
      successCount++;
    } catch (error) {
      console.log(`✗ Failed: ${topic.slug}`, error);
      failCount++;
    }
  }

  console.log(`\nKnowledge package generation complete: ${successCount} success, ${failCount} failed`);
}

generateKnowledgePackages()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Error:", error);
    process.exit(1);
  });
